apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.deployname }}-svc
  name: {{ .Values.deployname }}-svc
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.deployname }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetport }}