apiVersion: v1
kind: Service
metadata:
  labels:
    name: mjbsvc
  name: mjbsvc
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        another: example
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
